INSERT INTO FOOD(name, carb) VALUES('árpagyöngy', 75);
INSERT INTO FOOD(name, carb) VALUES('árpapehely', 44.5);
INSERT INTO FOOD(name, carb) VALUES('árpa (teljes árpaliszt)', 72);
INSERT INTO FOOD(name, carb) VALUES('zab (mag, teljes zabliszt)', 66.1);
INSERT INTO FOOD(name, carb) VALUES('zabpehely', 64.3);
INSERT INTO FOOD(name, carb) VALUES('búzacsíra', 42);
INSERT INTO FOOD(name, carb) VALUES('búzadara', 73.4);
INSERT INTO FOOD(name, carb) VALUES('búzakorpa (h.e.)', 15);
INSERT INTO FOOD(name, carb) VALUES('búzaliszt (finomított)', 76.3);
INSERT INTO FOOD(name, carb) VALUES('búzapehely', 32);
INSERT INTO FOOD(name, carb) VALUES('búza (teljes búzaliszt)', 64.4);
INSERT INTO FOOD(name, carb) VALUES('köles (hántolt)', 70.6);
INSERT INTO FOOD(name, carb) VALUES('kukoricaliszt és dara', 70.2);
INSERT INTO FOOD(name, carb) VALUES('kukoricapehely', 83);
INSERT INTO FOOD(name, carb) VALUES('rizs (hántolatlan)', 77.4);
INSERT INTO FOOD(name, carb) VALUES('rizs (hántolt, fényezett)', 77.5);
INSERT INTO FOOD(name, carb) VALUES('rozsliszt', 73.6);
INSERT INTO FOOD(name, carb) VALUES('rozspehely', 36.8);
INSERT INTO FOOD(name, carb) VALUES('Alma', 7);
INSERT INTO FOOD(name, carb) VALUES('Banán', 24.2);
INSERT INTO FOOD(name, carb) VALUES('Cseresznye', 14);
INSERT INTO FOOD(name, carb) VALUES('Datolya', 66.3);
INSERT INTO FOOD(name, carb) VALUES('Eper-szamóca', 7.2);
INSERT INTO FOOD(name, carb) VALUES('Málna', 5.4);
INSERT INTO FOOD(name, carb) VALUES('Görögdinnye', 6.5);
INSERT INTO FOOD(name, carb) VALUES('Grapefruit', 7.2);
INSERT INTO FOOD(name, carb) VALUES('Mandarin', 9.8);
INSERT INTO FOOD(name, carb) VALUES('Nektarin', 11.8);
INSERT INTO FOOD(name, carb) VALUES('Sárgadinnye', 9.5);
INSERT INTO FOOD(name, carb) VALUES('Szilva kék', 13.1);
INSERT INTO FOOD(name, carb) VALUES('Ringló szilva', 13.5);
INSERT INTO FOOD(name, carb) VALUES('Angolszalonna', 0);
INSERT INTO FOOD(name, carb) VALUES('Búzacsíraolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Császárszalonna', 0);
INSERT INTO FOOD(name, carb) VALUES('Élesztő', 0);
INSERT INTO FOOD(name, carb) VALUES('Füstölt szalonna', 0);
INSERT INTO FOOD(name, carb) VALUES('Hering', 0);
INSERT INTO FOOD(name, carb) VALUES('Kókuszzsír', 0);
INSERT INTO FOOD(name, carb) VALUES('Kukoricaolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Lenmag', 0);
INSERT INTO FOOD(name, carb) VALUES('Lenmag', 0);
INSERT INTO FOOD(name, carb) VALUES('Lenmagolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Libazsír', 0);
INSERT INTO FOOD(name, carb) VALUES('Napraforgó olaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Olajoshal konzerv', 0);
INSERT INTO FOOD(name, carb) VALUES('Olivaolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Paradics. halkonzerv', 0);
INSERT INTO FOOD(name, carb) VALUES('Pulykacomb', 0);
INSERT INTO FOOD(name, carb) VALUES('Pulykakolbász', 0);
INSERT INTO FOOD(name, carb) VALUES('Pulykamell', 0);
INSERT INTO FOOD(name, carb) VALUES('Repceolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Sertészsír', 0);
INSERT INTO FOOD(name, carb) VALUES('Szardínia', 0);
INSERT INTO FOOD(name, carb) VALUES('Szezámolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Szójaolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Tepertő', 0);
INSERT INTO FOOD(name, carb) VALUES('Tonhal filé', 0);
INSERT INTO FOOD(name, carb) VALUES('Tökmagolaj', 0);
INSERT INTO FOOD(name, carb) VALUES('Pirosarany', 0);
INSERT INTO FOOD(name, carb) VALUES('Ponty', 0.1);
INSERT INTO FOOD(name, carb) VALUES('Harcsa', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Keszeg', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Lazac', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Sertéspárizsi', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Sertésvirsli', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Sonkaszalámi', 0.2);
INSERT INTO FOOD(name, carb) VALUES('Füstölt főtt tarja', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Füstölt kolbász', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Kenőmájas', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Lecsókolbász', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Pecsenyeliba', 0.3);
INSERT INTO FOOD(name, carb) VALUES('sovány bárányhús', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Szárazkolbász', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Téliszalámi', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Tojás sárgája', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Túristaszalámi', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Vörösbor', 0.3);
INSERT INTO FOOD(name, carb) VALUES('Gépsonka', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Kacsahús', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Karaj sovány', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Margarin 35% zsírt.', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Margarin 55% zsírt', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Margarin 70 % zsírt', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Margarin-főző', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Nyúlhús', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Őzhús', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Sertéscomb sovány', 0.4);
INSERT INTO FOOD(name, carb) VALUES('sovány sertéshús,', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Tyúkhús', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Vaddisznóhús', 0.4);
INSERT INTO FOOD(name, carb) VALUES('Csirkecomb', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Csirkemell', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Fácánhús', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Rebarbara', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Vadkacsa', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Vaj', 0.5);
INSERT INTO FOOD(name, carb) VALUES('Busa', 0.6);
INSERT INTO FOOD(name, carb) VALUES('Ecet 20%-os', 0.6);
INSERT INTO FOOD(name, carb) VALUES('Tofu (szójatúró)', 0.6);
INSERT INTO FOOD(name, carb) VALUES('Tojás', 0.6);
INSERT INTO FOOD(name, carb) VALUES('Csirkeszív', 0.7);
INSERT INTO FOOD(name, carb) VALUES('Tojásfehérje', 0.7);
INSERT INTO FOOD(name, carb) VALUES('Saláta-endivia', 0.9);
INSERT INTO FOOD(name, carb) VALUES('Retek-fekete', 1);
INSERT INTO FOOD(name, carb) VALUES('Tőkehal filé', 1.2);
INSERT INTO FOOD(name, carb) VALUES('Juhsajt', 1.4);
INSERT INTO FOOD(name, carb) VALUES('Kókusztej', 1.4);
INSERT INTO FOOD(name, carb) VALUES('Sajt-göcseji', 1.4);
INSERT INTO FOOD(name, carb) VALUES('Krémsajt', 1.5);
INSERT INTO FOOD(name, carb) VALUES('Sajt-camembert', 1.5);
INSERT INTO FOOD(name, carb) VALUES('Sajt-ementáli', 1.5);
INSERT INTO FOOD(name, carb) VALUES('Sajt-köményes', 1.6);
INSERT INTO FOOD(name, carb) VALUES('Sajt-parmezán', 1.6);
INSERT INTO FOOD(name, carb) VALUES('Sajt-trappista', 1.6);
INSERT INTO FOOD(name, carb) VALUES('Snidling /metélőhagyma', 1.6);
INSERT INTO FOOD(name, carb) VALUES('Kígyóuborka', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Krémsajt camping', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Sajt-edámi', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Sajt-óvári', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Sajt-zalai füstölt', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Uborka', 1.7);
INSERT INTO FOOD(name, carb) VALUES('Olivabogyó', 1.8);
INSERT INTO FOOD(name, carb) VALUES('Sajt-anikó', 1.8);
INSERT INTO FOOD(name, carb) VALUES('Sajt-trapista', 1.8);
INSERT INTO FOOD(name, carb) VALUES('Spárga', 1.8);
INSERT INTO FOOD(name, carb) VALUES('Spenót /paraj', 1.8);
INSERT INTO FOOD(name, carb) VALUES('kenhető sajt', 1.9);
INSERT INTO FOOD(name, carb) VALUES('Kovászos uborka', 1.9);
INSERT INTO FOOD(name, carb) VALUES('Sajt-tenkes', 1.9);
INSERT INTO FOOD(name, carb) VALUES('Fejes saláta', 2);
INSERT INTO FOOD(name, carb) VALUES('Hóvirág-sajt', 2);
INSERT INTO FOOD(name, carb) VALUES('Kínaikel', 2);
INSERT INTO FOOD(name, carb) VALUES('Löncshús', 2);
INSERT INTO FOOD(name, carb) VALUES('Sajt-rokfort', 2);
INSERT INTO FOOD(name, carb) VALUES('Sajt-túra', 2);
INSERT INTO FOOD(name, carb) VALUES('Sajt-zsíros kockasajt', 2);
INSERT INTO FOOD(name, carb) VALUES('Brokkoli', 2.1);
INSERT INTO FOOD(name, carb) VALUES('Retek-hónapos', 2.2);
INSERT INTO FOOD(name, carb) VALUES('Cikória', 2.3);
INSERT INTO FOOD(name, carb) VALUES('Citrom', 2.3);
INSERT INTO FOOD(name, carb) VALUES('Sóska', 2.3);
INSERT INTO FOOD(name, carb) VALUES('Kecskesajt', 2.5);
INSERT INTO FOOD(name, carb) VALUES('Sertésmáj', 2.5);
INSERT INTO FOOD(name, carb) VALUES('Baromfipárizsi', 2.7);
INSERT INTO FOOD(name, carb) VALUES('Baromfivirsli', 2.7);
INSERT INTO FOOD(name, carb) VALUES('Juhtúró', 2.8);
INSERT INTO FOOD(name, carb) VALUES('Csirkemáj', 3);
INSERT INTO FOOD(name, carb) VALUES('Fehérbor', 3);
INSERT INTO FOOD(name, carb) VALUES('Gomolyatúró', 3);
INSERT INTO FOOD(name, carb) VALUES('Habtejszín', 3);
INSERT INTO FOOD(name, carb) VALUES('Zöldpaprika', 3);
INSERT INTO FOOD(name, carb) VALUES('Friss paradicsomlé', 3.1);
INSERT INTO FOOD(name, carb) VALUES('Tejszínkrémsajt', 3.1);
INSERT INTO FOOD(name, carb) VALUES('Gomba csiperke', 3.3);
INSERT INTO FOOD(name, carb) VALUES('Savanyúkáposzta', 3.4);
INSERT INTO FOOD(name, carb) VALUES('Tehéntúró félzsíros', 3.7);
INSERT INTO FOOD(name, carb) VALUES('Gomba vargánya', 3.8);
INSERT INTO FOOD(name, carb) VALUES('Író', 3.8);
INSERT INTO FOOD(name, carb) VALUES('sovány tehéntúró', 3.8);
INSERT INTO FOOD(name, carb) VALUES('Tejföl 20%-os', 3.8);
INSERT INTO FOOD(name, carb) VALUES('Karfiol', 3.9);
INSERT INTO FOOD(name, carb) VALUES('Kávétejszín', 3.9);
INSERT INTO FOOD(name, carb) VALUES('Csicsóka', 4);
INSERT INTO FOOD(name, carb) VALUES('Paradicsom', 4);
INSERT INTO FOOD(name, carb) VALUES('Sajt-feta', 4.1);
INSERT INTO FOOD(name, carb) VALUES('Pulykasonka', 4.2);
INSERT INTO FOOD(name, carb) VALUES('Kelkáposzta', 4.3);
INSERT INTO FOOD(name, carb) VALUES('Tejföl 12%-os', 4.3);
INSERT INTO FOOD(name, carb) VALUES('Joghurt', 4.6);
INSERT INTO FOOD(name, carb) VALUES('Joghurt 0%-os', 4.6);
INSERT INTO FOOD(name, carb) VALUES('Kefir', 4.6);
INSERT INTO FOOD(name, carb) VALUES('Kefrír / sovány', 4.6);
INSERT INTO FOOD(name, carb) VALUES('Világos sör', 4.6);
INSERT INTO FOOD(name, carb) VALUES('Kecsketej', 4.7);
INSERT INTO FOOD(name, carb) VALUES('Friss sárgarépalé', 4.8);
INSERT INTO FOOD(name, carb) VALUES('Kókuszdió friss', 4.8);
INSERT INTO FOOD(name, carb) VALUES('Padlizsán', 4.8);
INSERT INTO FOOD(name, carb) VALUES('Tej-0%-os', 4.8);
INSERT INTO FOOD(name, carb) VALUES('Juhtej', 5);
INSERT INTO FOOD(name, carb) VALUES('Zeller', 5);
INSERT INTO FOOD(name, carb) VALUES('Cukkini', 5.3);
INSERT INTO FOOD(name, carb) VALUES('Tej-1,5%-os', 5.3);
INSERT INTO FOOD(name, carb) VALUES('Tej-2,8%-os', 5.3);
INSERT INTO FOOD(name, carb) VALUES('Szójaszósz', 5.6);
INSERT INTO FOOD(name, carb) VALUES('Fejeskáposzta /téli', 5.7);
INSERT INTO FOOD(name, carb) VALUES('Lilakáposzta', 5.7);
INSERT INTO FOOD(name, carb) VALUES('Cékla', 5.9);
INSERT INTO FOOD(name, carb) VALUES('Petrezselyemgyökér', 5.9);
INSERT INTO FOOD(name, carb) VALUES('Gomba-laska', 6);
INSERT INTO FOOD(name, carb) VALUES('Szeder', 6);
INSERT INTO FOOD(name, carb) VALUES('Kelbimbó', 6.1);
INSERT INTO FOOD(name, carb) VALUES('Tök', 6.1);
INSERT INTO FOOD(name, carb) VALUES('Patisszon', 6.2);
INSERT INTO FOOD(name, carb) VALUES('Libamáj', 6.3);
INSERT INTO FOOD(name, carb) VALUES('Póréhagyma', 6.3);
INSERT INTO FOOD(name, carb) VALUES('Kókuszreszelék', 6.4);
INSERT INTO FOOD(name, carb) VALUES('Paradicsompaprika', 6.4);
INSERT INTO FOOD(name, carb) VALUES('Véreshurka', 6.4);
INSERT INTO FOOD(name, carb) VALUES('Mandula', 6.8);
INSERT INTO FOOD(name, carb) VALUES('Zöldbab', 6.8);
INSERT INTO FOOD(name, carb) VALUES('Karalábé', 6.9);
INSERT INTO FOOD(name, carb) VALUES('Csirkesonka', 7);
INSERT INTO FOOD(name, carb) VALUES('Ribizli-piros', 7);
INSERT INTO FOOD(name, carb) VALUES('Avokádó', 7.4);
INSERT INTO FOOD(name, carb) VALUES('Friss citromlé', 7.7);
INSERT INTO FOOD(name, carb) VALUES('Csipkebogyó', 8);
INSERT INTO FOOD(name, carb) VALUES('Egres', 8);
INSERT INTO FOOD(name, carb) VALUES('Tökmag', 8);
INSERT INTO FOOD(name, carb) VALUES('Sárgarépa', 8.1);
INSERT INTO FOOD(name, carb) VALUES('Sós földimogyoró', 8.3);
INSERT INTO FOOD(name, carb) VALUES('Vöröshagyma', 8.3);
INSERT INTO FOOD(name, carb) VALUES('Narancs', 8.5);
INSERT INTO FOOD(name, carb) VALUES('Friss grapefruitlé', 8.6);
INSERT INTO FOOD(name, carb) VALUES('Mogyoró /bokor/', 8.7);
INSERT INTO FOOD(name, carb) VALUES('Földimogyoró pörk.', 8.9);
INSERT INTO FOOD(name, carb) VALUES('Őszibarack', 9);
INSERT INTO FOOD(name, carb) VALUES('Birsalma', 9.1);
INSERT INTO FOOD(name, carb) VALUES('Ételízesítő', 9.3);
INSERT INTO FOOD(name, carb) VALUES('Szezámmag', 9.4);
INSERT INTO FOOD(name, carb) VALUES('Szezámmag', 9.4);
INSERT INTO FOOD(name, carb) VALUES('Szezámpehely', 9.4);
INSERT INTO FOOD(name, carb) VALUES('Articsóka', 9.5);
INSERT INTO FOOD(name, carb) VALUES('Ribizli-fekete', 9.5);
INSERT INTO FOOD(name, carb) VALUES('Papaya', 9.8);
INSERT INTO FOOD(name, carb) VALUES('Petrezselyemzöld', 9.8);
INSERT INTO FOOD(name, carb) VALUES('Sűrített tej édesítés nélk.', 9.8);
INSERT INTO FOOD(name, carb) VALUES('Kajszibarack', 10.2);
INSERT INTO FOOD(name, carb) VALUES('Kapor', 10.2);
INSERT INTO FOOD(name, carb) VALUES('Sárgabarack', 10.2);
INSERT INTO FOOD(name, carb) VALUES('Szilva', 10.2);
INSERT INTO FOOD(name, carb) VALUES('Kakaópor', 10.5);
INSERT INTO FOOD(name, carb) VALUES('Friss narancslé', 10.9);
INSERT INTO FOOD(name, carb) VALUES('Meggy', 11);
INSERT INTO FOOD(name, carb) VALUES('Cukordinnye', 11.1);
INSERT INTO FOOD(name, carb) VALUES('Kiwi', 11.3);
INSERT INTO FOOD(name, carb) VALUES('Dió', 11.7);
INSERT INTO FOOD(name, carb) VALUES('Ananász', 12);
INSERT INTO FOOD(name, carb) VALUES('Körte', 12);
INSERT INTO FOOD(name, carb) VALUES('Naspolya', 12);
INSERT INTO FOOD(name, carb) VALUES('Friss szőlőlé', 12.2);
INSERT INTO FOOD(name, carb) VALUES('Napraforgó mag', 12.3);
INSERT INTO FOOD(name, carb) VALUES('Pisztácia', 12.5);
INSERT INTO FOOD(name, carb) VALUES('Friss almalé', 14);
INSERT INTO FOOD(name, carb) VALUES('Maracuya', 14);
INSERT INTO FOOD(name, carb) VALUES('Zöldborsó', 14);
INSERT INTO FOOD(name, carb) VALUES('Fejeskáposzta /nyári', 14.7);
INSERT INTO FOOD(name, carb) VALUES('Füge friss', 15.5);
INSERT INTO FOOD(name, carb) VALUES('Torma', 15.9);
INSERT INTO FOOD(name, carb) VALUES('Sütőtök', 16.5);
INSERT INTO FOOD(name, carb) VALUES('Búzakorpa', 16.7);
INSERT INTO FOOD(name, carb) VALUES('Gránátalma', 16.7);
INSERT INTO FOOD(name, carb) VALUES('Licsi', 16.8);
INSERT INTO FOOD(name, carb) VALUES('Mangó', 17);
INSERT INTO FOOD(name, carb) VALUES('Joghurthab', 18);
INSERT INTO FOOD(name, carb) VALUES('Szőlő', 18.1);
INSERT INTO FOOD(name, carb) VALUES('Áfonya-fekete', 19.6);
INSERT INTO FOOD(name, carb) VALUES('Burgonya', 20);
INSERT INTO FOOD(name, carb) VALUES('Paradicsom püre', 20);
INSERT INTO FOOD(name, carb) VALUES('Szójapehely', 20);
INSERT INTO FOOD(name, carb) VALUES('Mustár', 22);
INSERT INTO FOOD(name, carb) VALUES('Szójaliszt', 22.1);
INSERT INTO FOOD(name, carb) VALUES('Csemegekukorica', 23.6);
INSERT INTO FOOD(name, carb) VALUES('Mák', 23.9);
INSERT INTO FOOD(name, carb) VALUES('Ketchup', 24);
INSERT INTO FOOD(name, carb) VALUES('Korpás-zsemle, kifli 1db', 24.5);
INSERT INTO FOOD(name, carb) VALUES('Fokhagyma', 26.3);
INSERT INTO FOOD(name, carb) VALUES('Szójabab', 27);
INSERT INTO FOOD(name, carb) VALUES('Fagylalt', 27.8);
INSERT INTO FOOD(name, carb) VALUES('Jégkrém', 27.8);
INSERT INTO FOOD(name, carb) VALUES('Kesudió olajos pörk', 28.5);
INSERT INTO FOOD(name, carb) VALUES('Zsemle/kifli 1db/5dkg', 28.5);
INSERT INTO FOOD(name, carb) VALUES('Fejtettbab', 29);
INSERT INTO FOOD(name, carb) VALUES('Szójagranulátum', 31);
INSERT INTO FOOD(name, carb) VALUES('Szójakocka', 31);
INSERT INTO FOOD(name, carb) VALUES('Szójaliszt zsírtalan', 31);
INSERT INTO FOOD(name, carb) VALUES('Szelídgesztenye', 32.6);
INSERT INTO FOOD(name, carb) VALUES('Tejpor-zsíros', 37);
INSERT INTO FOOD(name, carb) VALUES('Sajtos tallér', 39.1);
INSERT INTO FOOD(name, carb) VALUES('Búzacsíra', 42);
INSERT INTO FOOD(name, carb) VALUES('Csicseriborsó', 48.8);
INSERT INTO FOOD(name, carb) VALUES('Gesztenyemassza', 49.5);
INSERT INTO FOOD(name, carb) VALUES('Kenyér burgonyás', 49.7);
INSERT INTO FOOD(name, carb) VALUES('Kenyér rozsos', 49.9);
INSERT INTO FOOD(name, carb) VALUES('sovány tejpor', 50.3);
INSERT INTO FOOD(name, carb) VALUES('Kenyér barna', 50.6);
INSERT INTO FOOD(name, carb) VALUES('Kenyér félbarna', 52.3);
INSERT INTO FOOD(name, carb) VALUES('Tejcsokoládé', 52.8);
INSERT INTO FOOD(name, carb) VALUES('Lencse', 53);
INSERT INTO FOOD(name, carb) VALUES('Sárgaborsó', 53.1);
INSERT INTO FOOD(name, carb) VALUES('Rozskenyér', 53.6);
INSERT INTO FOOD(name, carb) VALUES('Kenyér graham', 54);
INSERT INTO FOOD(name, carb) VALUES('Nápolyi kakaós', 54.1);
INSERT INTO FOOD(name, carb) VALUES('Szárazbab', 54.1);
INSERT INTO FOOD(name, carb) VALUES('Kenyér lenmagos', 54.8);
INSERT INTO FOOD(name, carb) VALUES('Sűrített tej /cukrozott', 54.9);
INSERT INTO FOOD(name, carb) VALUES('Tejszín por', 54.9);
INSERT INTO FOOD(name, carb) VALUES('Aszalt alma', 55.4);
INSERT INTO FOOD(name, carb) VALUES('Tejcsokoládé', 56.8);
INSERT INTO FOOD(name, carb) VALUES('Zabkorpa', 57);
INSERT INTO FOOD(name, carb) VALUES('Pattog. Kukorica kész', 57.2);
INSERT INTO FOOD(name, carb) VALUES('Keksz sós', 58.3);
INSERT INTO FOOD(name, carb) VALUES('korpás-keksz', 59.8);
INSERT INTO FOOD(name, carb) VALUES('Borsóliszt', 60.5);
INSERT INTO FOOD(name, carb) VALUES('Sárgaborsóliszt', 60.5);
INSERT INTO FOOD(name, carb) VALUES('Rozspehely', 60.7);
INSERT INTO FOOD(name, carb) VALUES('Étcsokoládé', 62);
INSERT INTO FOOD(name, carb) VALUES('Fűszerpaprika', 63);
INSERT INTO FOOD(name, carb) VALUES('Búzapehely', 64);
INSERT INTO FOOD(name, carb) VALUES('Zabpehely', 64.3);
INSERT INTO FOOD(name, carb) VALUES('Grahamliszt', 64.4);
INSERT INTO FOOD(name, carb) VALUES('Búzaszelet puff.', 64.8);
INSERT INTO FOOD(name, carb) VALUES('Mazsola', 65);
INSERT INTO FOOD(name, carb) VALUES('Aszalt őszibarack', 65.9);
INSERT INTO FOOD(name, carb) VALUES('Köles', 68.8);
INSERT INTO FOOD(name, carb) VALUES('Müzli natúr', 70);
INSERT INTO FOOD(name, carb) VALUES('Aszalt sárgabarack', 70.2);
INSERT INTO FOOD(name, carb) VALUES('Kukoricadara', 70.2);
INSERT INTO FOOD(name, carb) VALUES('Kukoricaliszt', 70.2);
INSERT INTO FOOD(name, carb) VALUES('Burgonyapehely', 71);
INSERT INTO FOOD(name, carb) VALUES('Búza / hántolt', 71.1);
INSERT INTO FOOD(name, carb) VALUES('Hajdina', 71.3);
INSERT INTO FOOD(name, carb) VALUES('Árpaliszt', 72);
INSERT INTO FOOD(name, carb) VALUES('Száraztészta 4 toj.', 72.9);
INSERT INTO FOOD(name, carb) VALUES('Durum liszt', 73);
INSERT INTO FOOD(name, carb) VALUES('Durum tészta', 73);
INSERT INTO FOOD(name, carb) VALUES('Zsemlemorzsa', 73.3);
INSERT INTO FOOD(name, carb) VALUES('Búzadara', 73.4);
INSERT INTO FOOD(name, carb) VALUES('Rozsliszt', 73.6);
INSERT INTO FOOD(name, carb) VALUES('Árpagyöngy', 75);
INSERT INTO FOOD(name, carb) VALUES('Árpapehely', 75);
INSERT INTO FOOD(name, carb) VALUES('Ropi', 75);
INSERT INTO FOOD(name, carb) VALUES('Búzaliszt', 76.3);
INSERT INTO FOOD(name, carb) VALUES('Pászka', 76.3);
INSERT INTO FOOD(name, carb) VALUES('Rizs', 77.5);
INSERT INTO FOOD(name, carb) VALUES('Pattog. Kukorica natúr', 77.9);
INSERT INTO FOOD(name, carb) VALUES('Háztartási keksz', 78);
INSERT INTO FOOD(name, carb) VALUES('Keksz édes', 78.8);
INSERT INTO FOOD(name, carb) VALUES('Neskakaó', 79.1);
INSERT INTO FOOD(name, carb) VALUES('Kétszersült', 80.4);
INSERT INTO FOOD(name, carb) VALUES('Méz', 81);
INSERT INTO FOOD(name, carb) VALUES('Pótkávé', 81);
INSERT INTO FOOD(name, carb) VALUES('Barnarizs', 81.3);
INSERT INTO FOOD(name, carb) VALUES('Keksz abonett', 81.7);
INSERT INTO FOOD(name, carb) VALUES('Búzakeményítő', 82.5);
INSERT INTO FOOD(name, carb) VALUES('Kukoricapehely', 83);
INSERT INTO FOOD(name, carb) VALUES('Burgonyakeményítő', 83.1);
INSERT INTO FOOD(name, carb) VALUES('Barnacukor', 97.4);
